import type { ModeBuilderPreset } from "./modeBuilderTypes";

export const MODE_BUILDER_PRESETS: ModeBuilderPreset[] = [
  {
    id: "safe-helper",
    label: "Safe Helper",
    description: "Answers questions and reads files, but avoids risky actions by default.",
    base_mode: "ask",
    default_icon: "shield",
    default_system_prompt_append:
      "Prioritize clarity and safety. Explain intent before proposing any file edits.",
    default_allowed_tools: [
      "read",
      "search",
      "glob",
      "list",
      "websearch",
      "webfetch",
      "todowrite",
    ],
    default_edit_boundary: "none",
  },
  {
    id: "docs-writer",
    label: "Docs Writer",
    description: "Focused on docs and markdown updates with constrained write scope.",
    base_mode: "ask",
    default_icon: "book-open",
    default_system_prompt_append:
      "Focus on documentation quality, structure, and consistency. Keep code edits minimal.",
    default_allowed_tools: [
      "read",
      "search",
      "glob",
      "list",
      "websearch",
      "webfetch",
      "write",
      "edit",
      "create_file",
      "todowrite",
    ],
    default_edit_boundary: "docs",
  },
  {
    id: "research-only",
    label: "Research Only",
    description: "Investigates and summarizes, with no write permissions.",
    base_mode: "explore",
    default_icon: "search",
    default_system_prompt_append:
      "Research deeply, summarize findings, and avoid file changes unless explicitly reconfigured.",
    default_allowed_tools: [
      "read",
      "search",
      "glob",
      "list",
      "websearch",
      "webfetch",
      "todowrite",
    ],
    default_edit_boundary: "none",
  },
  {
    id: "strict-coder",
    label: "Strict Coder",
    description: "Code-focused mode with explicit edit boundaries.",
    base_mode: "coder",
    default_icon: "code",
    default_system_prompt_append:
      "Implement requested code changes with small diffs, strong validation, and concise rationale.",
    default_allowed_tools: [
      "read",
      "search",
      "glob",
      "list",
      "websearch",
      "webfetch",
      "write",
      "edit",
      "patch",
      "create_file",
      "delete_file",
      "todowrite",
    ],
    default_edit_boundary: "code",
  },
  {
    id: "code-reviewer",
    label: "Code Reviewer",
    description: "Reviews code and suggests improvements with minimal direct edits.",
    base_mode: "explore",
    default_icon: "clipboard-list",
    default_system_prompt_append:
      "Review code quality, risks, and maintainability. Prefer recommendations over broad rewrites.",
    default_allowed_tools: [
      "read",
      "search",
      "glob",
      "list",
      "websearch",
      "webfetch",
      "todowrite",
    ],
    default_edit_boundary: "none",
  },
  {
    id: "test-writer",
    label: "Test Writer",
    description: "Creates and refines tests in source and test directories.",
    base_mode: "coder",
    default_icon: "flask-conical",
    default_system_prompt_append:
      "Prioritize test coverage, deterministic tests, and clear assertions.",
    default_allowed_tools: [
      "read",
      "search",
      "glob",
      "list",
      "websearch",
      "webfetch",
      "write",
      "edit",
      "create_file",
      "patch",
      "todowrite",
    ],
    default_edit_boundary: "code",
  },
  {
    id: "planner",
    label: "Planner",
    description: "Generates actionable plans and phased implementation guidance.",
    base_mode: "plan",
    default_icon: "list-checks",
    default_system_prompt_append:
      "Produce structured, decision-complete plans with explicit assumptions and verification steps.",
    default_allowed_tools: [
      "read",
      "search",
      "glob",
      "list",
      "websearch",
      "webfetch",
      "todowrite",
    ],
    default_edit_boundary: "none",
  },
  {
    id: "orchestrator-assistant",
    label: "Orchestrator Assistant",
    description: "Coordinates multi-step work with controlled execution permissions.",
    base_mode: "orchestrate",
    default_icon: "sparkles",
    default_system_prompt_append:
      "Break work into clear phases and execute deliberately with guardrails.",
    default_allowed_tools: [
      "read",
      "search",
      "glob",
      "list",
      "websearch",
      "webfetch",
      "write",
      "edit",
      "patch",
      "create_file",
      "delete_file",
      "todowrite",
      "new_task",
      "update_todo_list",
    ],
    default_edit_boundary: "project",
  },
  {
    id: "release-notes",
    label: "Release Notes",
    description: "Drafts release notes, changelogs, and upgrade guidance.",
    base_mode: "ask",
    default_icon: "file-text",
    default_system_prompt_append:
      "Summarize changes clearly for users with concise highlights and migration notes.",
    default_allowed_tools: [
      "read",
      "search",
      "glob",
      "list",
      "websearch",
      "webfetch",
      "write",
      "edit",
      "create_file",
      "todowrite",
    ],
    default_edit_boundary: "docs",
  },
  {
    id: "runbook-assistant",
    label: "Runbook Assistant",
    description: "Builds operational runbooks and troubleshooting playbooks.",
    base_mode: "plan",
    default_icon: "clipboard-list",
    default_system_prompt_append:
      "Create operationally safe runbooks with prerequisites, rollback steps, and verification.",
    default_allowed_tools: [
      "read",
      "search",
      "glob",
      "list",
      "websearch",
      "webfetch",
      "write",
      "edit",
      "create_file",
      "todowrite",
    ],
    default_edit_boundary: "docs",
  },
  {
    id: "product-spec",
    label: "Product Spec",
    description: "Creates product specs and implementation-ready requirement docs.",
    base_mode: "plan",
    default_icon: "file-text",
    default_system_prompt_append:
      "Write clear product requirements with scope, acceptance criteria, and rollout constraints.",
    default_allowed_tools: [
      "read",
      "search",
      "glob",
      "list",
      "websearch",
      "webfetch",
      "write",
      "edit",
      "create_file",
      "todowrite",
    ],
    default_edit_boundary: "docs",
  },
  {
    id: "refactor-guard",
    label: "Refactor Guard",
    description: "Performs constrained refactors with strict path boundaries.",
    base_mode: "coder",
    default_icon: "wrench",
    default_system_prompt_append:
      "Keep refactors incremental, preserve behavior, and validate for regressions.",
    default_allowed_tools: [
      "read",
      "search",
      "glob",
      "list",
      "websearch",
      "webfetch",
      "write",
      "edit",
      "patch",
      "create_file",
      "todowrite",
    ],
    default_edit_boundary: "code",
  },
];

export function getModeBuilderPreset(presetId: string): ModeBuilderPreset {
  return MODE_BUILDER_PRESETS.find((preset) => preset.id === presetId) ?? MODE_BUILDER_PRESETS[0];
}


