schema_version = 1
generated_at = "2026-03-02T23:03:19.833Z"
source = "anthropic-mcp-registry"
catalog_version = "latest"
catalog_visibility = "commercial"
pack_id = "mcp.remote.hugging-face"
slug = "hugging-face"
name = "Hugging Face"
description = "Access the Hugging Face Hub and thousands of Gradio Apps"
documentation_url = "https://huggingface.co/settings/mcp"
directory_url = "https://claude.ai/directory/37ed56d5-9d61-4fd4-ad00-b9134c694296"
requires_auth = true
requires_setup = false
works_with = ["claude", "claude-api", "claude-code"]
use_cases = ["code"]
tool_names = ["hf_whoami", "space_search", "model_search", "model_details", "paper_search", "dataset_search", "dataset_details", "hf_doc_search", "gr1_flux1_schnell_infer", "gr2_0_abidlabs_easyghiblis_ndition_generate_image"]
visibility = ["commercial"]

[server]
name = "co.huggingface/hf-mcp-server"
version = "0.2.33"
display_name = "Hugging Face"
transport_url = "https://huggingface.co/mcp?login&gradio=none"

[registry]
uuid = "37ed56d5-9d61-4fd4-ad00-b9134c694296"
rank = 22
author_name = "Hugging Face"
author_url = "https://huggingface.co/"
published_on = "Mon Jan 12 2026 16:21:41 GMT+0000 (Coordinated Universal Time)"
updated_on = "Mon Jan 12 2026 16:20:13 GMT+0000 (Coordinated Universal Time)"

[[remote]]
type = "streamable-http"
url = "https://huggingface.co/mcp?login&gradio=none"
